# MineTutor Configuration

# OpenAI API Key
# Get your API key from https://beta.openai.com/account/api-keys
ai-provider: openai
api-key: YOUR_OPENAI_API_KEY

# The system prompt helps set the behavior of the assistant.
# You can modify this to change how MineTutor responds.
system-prompt: "You are MineTutor, a helpful Minecraft expert. Answer the user's questions about Minecraft concisely and accurately. Your response should be in Korean."

# Cooldown in seconds between uses of the /guide command for each player.
command-cooldown: 30

# Messages
messages:
  cooldown: "§cYou must wait {time} more seconds before using this command again."
  thinking: "§eMineTutor is thinking..."
  error: "§cError: Failed to get response from MineTutor."
  no-permission: "§cYou do not have permission to use this command."
  usage: "§cUsage: /guide <question>"
